name: Tribu
main: graindcafe.tribu.Tribu
version: B.5.0.12514
commands:
    tribu:
        description: start,stop, join, leave, the game, create, save, load, levels. 
        usage: /tribu enter | leave | vote <1|2> | stats
    zspawn:
        description: creates a zombie spawnpoint at the current location. Use [jump] <name> to jump to the spawn
        usage: /zspawn (( set | remove | jump ) <name> ) | list
    dspawn:
        description: sets the death spawnpoint. Use [jump] to jump to the spawn
        usage: /dspawn [jump]
    ispawn:
        description: sets the initial spawnpoint. Use [jump] to jump to the spawn
        usage: /ispawn [jump]
permissions:
    tribu.*:
        description: All commands
        children:
            tribu.use: true
            tribu.level: true
            tribu.game: true
            tribu.plugin: true
            tribu.signs: true
    tribu.use:
        description: Player commands 
        children:
            tribu.use.enter: true
            tribu.use.leave: true
            tribu.use.vote: true
            tribu.use.stats: true
    tribu.use.enter:
        description: Enter the game
        default: true
    tribu.use.leave:
        description: Leave the game
        default: true
    tribu.use.vote:
        description: Vote
        default: true
    tribu.use.stats:
        description: Display stats
        default: true
    tribu.level:
        description: Level management commands
        children:
            tribu.level.package: true
            tribu.level.create: true
            tribu.level.delete: true
            tribu.level.load: true
            tribu.level.unload: true
            tribu.level.save: true
            tribu.level.list: true
            tribu.level.zspawn: true
            tribu.level.dspawn: true
            tribu.level.ispawn: true
    tribu.level.package:
        description: Manage packages
        default: op
    tribu.level.create:
        description: Create a level
        default: op
    tribu.level.delete:
        description: Delete a level
        default: op
    tribu.level.load:
        description: Load a level
        default: op
    tribu.level.unload:
        description: Delete a level
        default: op
    tribu.level.save:
        description: Save a level
        default: op
    tribu.level.list:
        description: List levels
        default: op
    tribu.level.zspawn:
        description: Manage zombies spawn
        default: op
    tribu.level.dspawn:
        description: Set death spawn
        default: op
    tribu.level.ispawn:
        description: Set initial spawn
        default: op
    tribu.signs:
        description: Manage the signs
        default: op
        children:
          tribu.signs.break: true
          tribu.signs.place: true
    tribu.signs.place:
        description: Can place a sign
        default: op
    tribu.signs.break:
        description: Can break a sign
        default: op
    tribu.game:
        description: Manage the game
        children:
          tribu.game.start: true
          tribu.game.stop: true
    tribu.game.start:
        description: Start the game
        default: op
    tribu.game.stop:
        description: Stop the game
        default: op
    tribu.plugin:
        description: Manage the plugin
        default: op
    tribu.plugin.reload:
        description: Reload config
        default: op